FROM openjdk:8-jre-alpine

LABEL maintainer="Andrei Varabyeu <andrei_varabyeu@epam.com>"
LABEL version="4.0.0"
LABEL description="@description@"

ENV JAVA_OPTS="-Xmx256m -Djava.security.egd=file:/dev/./urandom"
ENV JAVA_APP=/app.jar

RUN echo $'#!/bin/sh \n\
exec java $JAVA_OPTS -jar $JAVA_APP' > /start.sh && chmod +x /start.sh

VOLUME /tmp
ADD service-jira-4.0.0.jar $JAVA_APP

RUN sh -c 'touch $JAVA_APP'

EXPOSE 8080

ENTRYPOINT ["/start.sh"]

